### ISSUE TITLE
Working plan for 07/03

### ISSUE THREAD

**Issue by LinlinYin** [LinlinYin/mlr3vis#10]
**- Update mlr3vis to latest version of mlr3.** 
Because of  mlr3's update, Experiment object is removed. So almost all functions in mlr3vis need to be changed (as I used Experiment object in almost all functions to get data). This will takes a while to fix. And will also re-run vignette and tests, and make sure they are correct.

**- Fix ongoing issues** 
There are a few ongoing issues, including issue #3 and #5, will fix these issues

**- Update more introductions for NOT reviewed functions and ask for review.** 
There are a few functions programmed but not reviewed by mentors, including issue #8 #7. Will write more introductions and asks for review of them.

**- Propose and test one new function** 
I have proposed a few topics in to-do list of this plan (Model Optimization or Feature selection). Will propose and test one new function among these new features.

**Comment by larskotthoff** [comment]
Thanks, as I've said on slack, please create a document first that explains, documents, and illustrates the functions that you've already implemented first please. It's very difficult for us to give you feedback on what you're doing because you're not explaining what you're doing and there's only minimal documentation without examples.

**Comment by LinlinYin** [comment]
Thank you! We have a lot discussion in slack today. Some documents was already in vignette and will add more details to it.

See comments below for works today and will close this issue, moving unfinished issues to tomorrow.

1. **Update mlr3vis to latest version of mlr3.**
This is ongoing and plotLearnerPrediction is working now and more introduction added to vignette ;
2. **Fix ongoing issues**
#3 is related to point 1 and onging. Function of #5 is there and will add more introduction to vignette for it.
3. **Update more introductions for NOT reviewed functions and ask for review.**
Also related to add more introduction to vignette.
4. **Propose and test one new function**
Proposed summaryFeatureInTask and plotFeatureInTask. Will add more introduction to vignette.
