### ISSUE TITLE
Set default theme?

### ISSUE THREAD

**Issue by pat-s** [LinlinYin/mlr3vis#6]
`ggpubr::theme_pubr()` is our fav theme also in the courses.
Should we import it and use it as the default?

This is a discussion that will probably never be solved (going with ggplot2 defaults or changing it in the package).

I would vote for changing the default theme supporting the option to append any `+ theme_X()` call to any `plot*()` function in `mlr3viz`.

**Comment by LinlinYin** [comment]
Thanks! I agree with this theme idea. Maybe we can make it as an overall option for all visualization functions? I checked ggpubr documents at https://rpkgs.datanovia.com/ggpubr/reference/index.html, which theme should we choose? What about theme_pubr()?

My question is how to make this this work? Making a function and call it at the end of all mlr3vis functions, such as 

> plotWithTheme=function (p) {return(p+theme_pubr())}

**Comment by pat-s** [comment]
Yes, `ggpubr::theme_pubr()` as I suggested it above.

Take a look at `?ggplot2::theme_set()`.
When loading the package we should inform the user about this default.
Changing it could be supported through a global option like `options("mlr_plot_theme = <theme>"`.

**Comment by LinlinYin** [comment]
I added some codes in zzz.r to change the global options, and the theme was also changed. 
Not sure if it is a good idea to change the theme globally when loading the package?

**Comment by pat-s** [comment]
You're right, a global change is not so smart.

The approach here looks simple and easy:

https://github.com/kassambara/ggcorrplot/blob/58cfb3a849486f6f479b1b2786a0c1f2a4b82b04/R/ggcorrplot.R#L246-L251

**Comment by LinlinYin** [comment]
Thanks! This has been applied in `plotBMRBoxplots `and `plotBMRRanksAsBarChart`. Please review `zzz.R` for `plotWithTheme `function with application of `theme_pubr`.
